[#6] MVVM, Data Binding 적용
f-lab-edu/electric-car-charge-info pull request #7
Opened 2022-08-24 06:24 UTC by aabc88

### Related Issues

- In Progress https://github.com/f-lab-edu/electric-car-charge-info/issues/6

### Description
- MVVM, Data Binding 적용

### 변경 사항
- MVVM, Data Binding 적용

### 질문 사항
-

### 기타
-

2022-09-01 15:14 UTC, aabc88 commented
### Related Issues

- In Progress https://github.com/f-lab-edu/electric-car-charge-info/issues/6

### Description
- Binding adapter적용, 버튼글자 깨짐 해결

### 변경 사항
- - Binding adapter적용, 버튼글자 깨짐 해결

### 질문 사항
-

### 기타
-

2022-09-07 07:08 UTC, f-lab-liam requested changes

2022-09-07 07:08 UTC, f-lab-liam commented on app/src/main/java/com/example/ecarchargeinfo/binding/TestBindingAdapter.kt
> +}
파일들에 마지막에 빈 라인 추가해주세요.

2022-09-07 07:08 UTC, f-lab-liam commented
Magic Number 제거해주세요.

2022-09-14 07:07 UTC, merged